src/accounts/urls.py
from django.urls import  path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),

    path('verify-email/<uidb64>/<token>/', views.verify_email, name='verify_email'),
]

src/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.welcome_view, name='welcome'),
    path('accounts/', include('accounts.urls')),
    path('profiles/', include('profiles.urls')),
    path('mentors/', include('mentors.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/mentors/urls.py
from django.urls import path

from . import views

app_name = 'mentors'

urlpatterns = [
    path('', views.mentors_list, name='mentors_list'),
    path('profile-overview/<str:username>/', views.profile_overview, name='profile_overview'),
    path('profile/<str:username>/', views.mentor_profile, name='mentor_profile'),
]

src/profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('register-choice/', views.register_choice, name='register_choice'),

    path('register-user/', views.register, kwargs={'role': 'user'}, name='register_user'),
    path('register-mentor/', views.register, kwargs={'role': 'mentor'}, name='register_mentor'),

    path('edit-profile/', views.edit_profile, name='edit_profile'),
]

src/templates/includes/footer.html
<footer class="footer text-center mt-4">
    <p>&copy; 2025 Snugly. Made with love by <strong>DeviantCoder</strong></p>
</footer>

src/templates/includes/messages.html
{% if messages %}
    <div class="d-flex justify-content-center w-100 fixed-top" style="z-index: 1050; margin-top: 30px;">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} radius-md border-0 shadow-lg mt-2 alert-dismissible fade show text-center" role="alert"
                style="max-width: 300px;">
                <strong>{{ message }}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    </div>
{% endif %}

src/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm sticky-top">
    <div class="container">
        <a class="navbar-brand fw-bold" href="/"><i class="bi bi-chat-heart h5"></i> Snugly</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                {% if request.user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link hover-grow-sm" href="#"><i class="bi bi-house-door"></i>
                            Home</a></li>
                    <li class="nav-item"><a class="nav-link hover-grow-sm" href="#"><i class="bi bi-chat-dots"></i>
                            Chats</a></li>
                    <li class="nav-item">
                        <a class="nav-link hover-grow-sm" href="{% url 'mentors:mentors_list' %}">
                            <i class="bi bi-person-check"></i>
                            Mentors
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link hover-grow-sm" href="">
                            <i class="bi bi-columns"></i>
                            Dashboard
                        </a>
                    </li>
                    
                    <li class="nav-item">
                        {% if request.user.role == 'admin' %}
                            <a class="nav-link hover-grow-sm" href="{% url 'admin:index' %}"><i class="bi bi-gear"></i> Admin Panel</a>
                        {% else %}
                            <div class="dropdown">
                                <button class="nav-link hover-grow-sm dropdown-toggle" type="button" data-bs-toggle="dropdown"
                                    aria-expanded="false">
                                    <i class="bi bi-person"></i>
                                    Profile
                                </button>    
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="dropdown-item" href="">
                                            <i class="bi bi-person me-2"></i> View Profile
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="{% url 'profiles:edit_profile' %}">
                                            <i class="bi bi-pencil-square me-2"></i> Edit Profile
                                        </a>
                                    </li>
                                    <hr>
                                    <li>
                                        <a class="dropdown-item text-danger" href="{% url 'accounts:logout' %}">
                                            <i class="bi bi-box-arrow-right me-2"></i> Log out
                                        </a>
                                    </li>
                                </ul>                      
                            </div>
                        {% endif %}  
                    </li>

                {% endif %}
                <li class="nav-item"><a class="nav-link hover-grow-sm" href="#"><i class="bi bi-question-circle"></i>
                        Help</a></li>
            </ul>
        </div>
    </div>
</nav>

src/templates/includes/pagination.html
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center mt-4">
        <li class="page-item disabled">
            <a class="page-link border-0" href="#" aria-label="Previous">
                <i class="bi bi-chevron-left"></i>
            </a>
        </li>
        <li class="page-item active"><a class="page-link border-0" href="#">1</a></li>
        <li class="page-item"><a class="page-link border-0" href="#">2</a></li>
        <li class="page-item"><a class="page-link border-0" href="#">3</a></li>
        <li class="page-item">
            <a class="page-link border-0" href="#" aria-label="Next">
                <i class="bi bi-chevron-right"></i>
            </a>
        </li>
    </ul>
</nav>